name: JBZD Imiona Scraper

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job-index: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install requests
        run: pip install requests

      - name: Run scraper job
        run: python scraper.py ${{ matrix.job-index }}

  merge:
    needs: scrape
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Merge results
        run: python scraper.py --merge

      - name: Upload final CSV
        uses: actions/upload-artifact@v3
        with:
          name: wyniki_final
          path: wyniki_final.csv
